"use client"

import {BarChart,Bar,XAxis,YAxis,CartesianGrid,Cell,} from "recharts"
import {ChartContainer,ChartTooltip,ChartTooltipContent,} from "@/components/ui/chart"

const CYAN = "#0EA5E9"

const chartConfig = {
  receita: {
    label: "Receita",
    color: CYAN,
  },
}

interface TopClientsChartProps {
  data: TopClients[]
}

export function TopClientsChart({ data }: TopClientsChartProps) {
  return (
    <div className="animate-fade-in-up rounded-xl border border-border bg-card p-5" style={{ animationDelay: "800ms", animationFillMode: "backwards" }}>
      <h3 className="mb-1 text-base font-semibold text-foreground">
        Top 5 Clients
      </h3>
      <p className="mb-4 text-sm text-muted-foreground">
        Highest revenue generated by client
      </p>
      <ChartContainer config={chartConfig} className="h-[280px] w-full">
        <BarChart
          data={data}
          layout="vertical"
          margin={{ top: 5, right: 10, left: 10, bottom: 0 }}
        >
          <CartesianGrid strokeDasharray="3 3" stroke="#334155" horizontal={false} />
          <XAxis
            type="number"
            stroke="#94A3B8"
            fontSize={12}
            tickLine={false}
            axisLine={false}
            tickFormatter={(value) =>
              `${(value / 1000).toFixed(0)}K`
            }
          />
          <YAxis
            type="category"
            dataKey="client"
            stroke="#94A3B8"
            fontSize={11}
            tickLine={false}
            axisLine={false}
            width={110}
          />
          <ChartTooltip
            content={
              <ChartTooltipContent
                formatter={(value) => (
                  <span className="font-mono text-foreground">
                    R$ {Number(value).toLocaleString("pt-BR")}
                  </span>
                )}
              />
            }
          />
          <Bar
            dataKey="revenue"
            radius={[0, 6, 6, 0]}
            name="revenue"
          >
            {data.map((_, index) => (
              <Cell
                key={`cell-${index}`}
                fill={CYAN}
                fillOpacity={1 - index * 0.15}
              />
            ))}
          </Bar>
        </BarChart>
      </ChartContainer>
    </div>
  )
}
